version=0.0

[default.global.parameters]
stack_name = "Test-Lambda-Function-Stack"

[default.deploy.parameters]
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
s3_prefix = "cloud-technology-sam-local-deployments"
tags = "Organization=\"Cloud-Technology\" Environment=\"Development\" TF=\"False\" State=\"False\""

[default.build.parameters]
container_env_var = []
# container_env_var_file = "env.json"
no_beta_features = false
